server {
    listen 80;
    server_name hotelqr.iotsoft.in;
    root /var/www/hotelqr-marketing;
    index index.html;
    location /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 80;
    server_name hotelqr.admin.iotsoft.in;
    root /var/www/hotel-admin;
    index index.html;
    location /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 80;
    server_name hotelqr.kds.iotsoft.in;
    root /var/www/hotel-kds;
    index index.html;
    location /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 80;
    server_name hotelqr.waiter.iotsoft.in;
    root /var/www/hotel-waiter;
    index index.html;
    location /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { try_files $uri $uri/ /index.html; }
}
